ckanext-toolsfrontend: Remove related_item stats snippet
The "related" database tables were deprecated in CKAN 2.6 and this
now causes an error:

    UndefinedError: 'dict object' has no attribute 'related_count'